name: rss_app
description: A sample Chrome packaged application
dependencies:
  angular: any
  chrome: any
  web_components: any
transformers:
- chrome
- angular:
    csp: true
- $dart2js:
    checked: false
    minify: false
    verbose: false
    analyzeAll: false
    suppressWarnings: false
    suppressHints: false
    terse: false
