/* 
 * Copyright 2014 Paweł Psztyć.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

function Feed() {
    this.feedid = null;
    this.title = null;
    this.subtitle = null;
    this.updated = null;
    this.author = null; /* FeedAuthor */
    this.totalItems = -1;
    this.categories = [];
    this.entries = []; /* [FeedEntry] */
    this.etag = null;
    this.pageurl = null;

    this.toJson = function() {
        var entries = [];
        for (var i = 0, len = this.entries.length; i < len; i++) {
            entries[entries.length] = this.entries[i].toJson();
        }
        var author = null;
        if (this.author !== null) {
            author = this.author.toJson();
        }
        
        return {
            'feedid': this.feedid,
            'title': this.title,
            'subtitle': this.subtitle,
            'pageurl': this.pageurl,
            'updated': this.updated,
            'author': author,
            'totalItems': this.totalItems,
            'categories': this.categories,
            'entries': entries,
            'etag': this.etag
        };
    };
}

function FeedAuthor() {
    this.name = null;
    this.email = null;
    this.image = {
        'src': null,
        'width': null,
        'height': null
    };
    this.url = null;

    this.toJson = function() {
        return {
            'name': this.name,
            'email': this.email,
            'image': this.image,
            'url': this.url
        };
    };
}

function FeedEntry() {
    /**
     * The entry ID from feed data.
     * Internal database ID is an "id" attribute autogenerated by the datastore.
     */
    this.entryid = null;
    /**
     * Publication date
     * @type String
     */
    this.published = null;
    /**
     * Update time.
     * @type String
     */
    this.updated = null;
    /**
     * Entry title.
     * @type String
     */
    this.title = null;
    /**
     * @type String
     */
    this.content = null;
    /**
     * @type String
     */
    this.url = null;
    /**
     * @type Object FeedAuthor
     */
    this.author = null; /* FeedAuthor */
    /**
     * @type Array of String
     */
    this.categories = [];
    /**
     * @type Object
     */
    this.thumbnail = {
        'src': null,
        'width': null,
        'height': null
    };
    this['new'] = 1;
    this.unread = 1;
    this.starred = 0;
    /**
     * A special field with a timestamp of FeedEntry.published time.
     * It is generated only once by sync service and will be used by the app to 
     * compare FeedEntry objects in the array so it can be ordered by the 
     * publication date.
     */
    this.createtime = 0;

    this.toJson = function() {
        var author = null;
        if (this.author !== null) {
            author = this.author.toJson();
        }
        return {
            'entryid': this.entryid,
            'published': this.published,
            'updated': this.updated,
            'title': this.title,
            'content': this.content,
            'url': this.url,
            'author': author,
            'categories': this.categories,
            'new': this['new'],
            'unread': this.unread,
            'starred': this.starred,
            'createtime': this.createtime
        };
    };
}